/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.WindowConstants;

/**
 *
 * @author johnpaulquijano
 */
public class ClientUI extends javax.swing.JFrame {

    /**
     * Creates new form ClientUI
     */
    public ClientUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consoleDialog = new JDialog();
        consolePanel = new JPanel();
        consoleScrollPane = new JScrollPane();
        consoleTextPane = new JTextPane();
        consoleTextField = new JTextField();
        consoleButton = new JButton();
        gamePanel = new JPanel();

        consoleDialog.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        consoleDialog.setTitle("Console");
        consoleDialog.setAlwaysOnTop(true);
        consoleDialog.setName(""); // NOI18N
        consoleDialog.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent evt) {
                consoleDialogWindowClosing(evt);
            }
        });

        consoleTextPane.setEditable(false);
        consoleScrollPane.setViewportView(consoleTextPane);

        consoleTextField.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                consoleTextFieldKeyPressed(evt);
            }
        });

        consoleButton.setText("Enter");
        consoleButton.setFocusPainted(false);
        consoleButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                consoleButtonActionPerformed(evt);
            }
        });

        GroupLayout consolePanelLayout = new GroupLayout(consolePanel);
        consolePanel.setLayout(consolePanelLayout);
        consolePanelLayout.setHorizontalGroup(consolePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(consoleScrollPane)
            .addGroup(consolePanelLayout.createSequentialGroup()
                .addComponent(consoleTextField, GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(consoleButton, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE))
        );
        consolePanelLayout.setVerticalGroup(consolePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(consolePanelLayout.createSequentialGroup()
                .addComponent(consoleScrollPane, GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(consolePanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(consoleTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(consoleButton, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)))
        );

        GroupLayout consoleDialogLayout = new GroupLayout(consoleDialog.getContentPane());
        consoleDialog.getContentPane().setLayout(consoleDialogLayout);
        consoleDialogLayout.setHorizontalGroup(consoleDialogLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(consolePanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        consoleDialogLayout.setVerticalGroup(consoleDialogLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(consolePanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setName(""); // NOI18N
        setUndecorated(true);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        GroupLayout gamePanelLayout = new GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(gamePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        gamePanelLayout.setVerticalGroup(gamePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(gamePanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(gamePanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consoleTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_consoleTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_consoleTextFieldKeyPressed

    private void consoleButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_consoleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consoleButtonActionPerformed

    private void consoleDialogWindowClosing(WindowEvent evt) {//GEN-FIRST:event_consoleDialogWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_consoleDialogWindowClosing

    private void formWindowClosing(WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static JButton consoleButton;
    private static JDialog consoleDialog;
    private static JPanel consolePanel;
    private static JScrollPane consoleScrollPane;
    private static JTextField consoleTextField;
    private static JTextPane consoleTextPane;
    private static JPanel gamePanel;
    // End of variables declaration//GEN-END:variables
}
