/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.WindowConstants;

/**
 *
 * @author johnpaulquijano
 */
public class ServerConsole extends javax.swing.JFrame {

    /**
     * Creates new form ServerConsole
     */
    public ServerConsole() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serverConsolePanel = new JPanel();
        serverConsoleScrollPane = new JScrollPane();
        severConsoleTextPane = new JTextPane();
        serverConsoleTextField = new JTextField();
        serverConsoleButton = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Server Console");
        setAlwaysOnTop(true);
        setMinimumSize(new Dimension(500, 400));

        severConsoleTextPane.setEditable(false);
        serverConsoleScrollPane.setViewportView(severConsoleTextPane);

        serverConsoleTextField.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                serverConsoleTextFieldKeyPressed(evt);
            }
        });

        serverConsoleButton.setText("Enter");
        serverConsoleButton.setFocusPainted(false);
        serverConsoleButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                serverConsoleButtonActionPerformed(evt);
            }
        });

        GroupLayout serverConsolePanelLayout = new GroupLayout(serverConsolePanel);
        serverConsolePanel.setLayout(serverConsolePanelLayout);
        serverConsolePanelLayout.setHorizontalGroup(serverConsolePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(serverConsoleScrollPane)
            .addGroup(serverConsolePanelLayout.createSequentialGroup()
                .addComponent(serverConsoleTextField, GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(serverConsoleButton, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE))
        );
        serverConsolePanelLayout.setVerticalGroup(serverConsolePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(serverConsolePanelLayout.createSequentialGroup()
                .addComponent(serverConsoleScrollPane, GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(serverConsolePanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(serverConsoleTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(serverConsoleButton, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(serverConsolePanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(serverConsolePanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serverConsoleButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_serverConsoleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serverConsoleButtonActionPerformed

    private void serverConsoleTextFieldKeyPressed(KeyEvent evt) {//GEN-FIRST:event_serverConsoleTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_serverConsoleTextFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerConsole().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static JButton serverConsoleButton;
    private static JPanel serverConsolePanel;
    private static JScrollPane serverConsoleScrollPane;
    private static JTextField serverConsoleTextField;
    private static JTextPane severConsoleTextPane;
    // End of variables declaration//GEN-END:variables
}
